In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.3'

## Create & Read

#### 1D Array

In [43]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [6]:
type(arr1)

numpy.ndarray

In [8]:
arr1.shape

(4,)

In [9]:
arr1.dtype

dtype('int64')

In [10]:
arr1.ndim

1

In [11]:
arr1.size

4

#### 2D Array

In [12]:
arr2 = np.array([[1,4,5],[6,7,4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape ##(row, col)

(2, 3)

In [15]:
arr2.dtype

dtype('int64')

In [19]:
arr2.size

6

#### 3D Array

In [23]:
arr3 = np.array([[[1,4,5],[6,7,4]],[[3,5,4],[5,8,7]],[[2,3,4],[5,6,7]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[2, 3, 4],
        [5, 6, 7]]])

In [24]:
arr3.ndim

3

In [25]:
arr3.shape

(3, 2, 3)

In [27]:
arr3.size

18

# Create random array

In [28]:
randomArr = np.random.rand(3,2,3)
randomArr

array([[[0.73773363, 0.05486527, 0.66193115],
        [0.03591361, 0.87188725, 0.81753459]],

       [[0.78234302, 0.31397946, 0.29289268],
        [0.08657381, 0.33167537, 0.88900726]],

       [[0.41756491, 0.75160899, 0.57949061],
        [0.48232933, 0.43424418, 0.67232635]]])

In [29]:
randomArr.dtype

dtype('float64')

In [31]:
zeroes = np.zeros((3,2,3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [32]:
zeroes.ndim

3

In [33]:
full = np.full((3,2,3),5)
full

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

In [34]:
full.dtype

dtype('int64')

In [35]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [36]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[2, 3, 4],
        [5, 6, 7]]])

In [40]:
arr3[1][1][1]

np.int64(8)

In [41]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [45]:
arr3[1,1,1]

np.int64(8)

# Update & Delete

In [48]:
a1 = np.random.rand(2,3,2)
a2 = np.random.rand(2,3,2)

In [49]:
a1

array([[[0.40484055, 0.5467942 ],
        [0.20321044, 0.7296715 ],
        [0.60789951, 0.7490405 ]],

       [[0.65193373, 0.11861578],
        [0.93481164, 0.64544033],
        [0.39453462, 0.9959059 ]]])

In [50]:
a2

array([[[0.91211812, 0.86740069],
        [0.80967195, 0.22545664],
        [0.33362586, 0.83306265]],

       [[0.18270548, 0.60152725],
        [0.74512958, 0.81827719],
        [0.76279542, 0.45427245]]])

#### Basic Math Operations

In [55]:
np.add(a1,a2)

array([[[1.31695868, 1.41419489],
        [1.01288238, 0.95512815],
        [0.94152537, 1.58210316]],

       [[0.83463921, 0.72014302],
        [1.67994122, 1.46371752],
        [1.15733004, 1.45017836]]])

In [56]:
np.subtract(a1,a2)

array([[[-0.50727757, -0.32060648],
        [-0.60646151,  0.50421486],
        [ 0.27427365, -0.08402215]],

       [[ 0.46922826, -0.48291147],
        [ 0.18968206, -0.17283685],
        [-0.3682608 ,  0.54163345]]])

In [57]:
np.divide(a1,a2)

array([[[0.44384663, 0.63038249],
        [0.25097873, 3.23641608],
        [1.82209951, 0.89914066]],

       [[3.56822218, 0.19719103],
        [1.25456251, 0.78877958],
        [0.51722206, 2.19230969]]])

In [58]:
np.multiply(a1,a2)

array([[[0.36926241, 0.47428966],
        [0.16453379, 0.16450929],
        [0.202811  , 0.62399767]],

       [[0.11911186, 0.07135062],
        [0.6965558 , 0.5281491 ],
        [0.3009492 , 0.45241262]]])

#### Statistical Operations

In [60]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [61]:
sqrt

np.float64(5.0)

In [62]:
abs

np.int64(2)

In [63]:
power

np.int64(256)

In [64]:
log

np.float64(3.2188758248682006)

In [65]:
mins

np.float64(0.11861577808895152)

In [66]:
maxs

np.float64(0.9121181217070938)

#### Update

In [67]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[2, 3, 4],
        [5, 6, 7]]])

In [68]:
arr3[0,1,2] = 9

In [69]:
arr3

array([[[1, 4, 5],
        [6, 7, 9]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[2, 3, 4],
        [5, 6, 7]]])

In [70]:
arr3.sort()
arr3

array([[[1, 4, 5],
        [6, 7, 9]],

       [[3, 4, 5],
        [5, 7, 8]],

       [[2, 3, 4],
        [5, 6, 7]]])

#### Reshape

In [71]:
arr3.shape

(3, 2, 3)

In [73]:
arr3_reshape = arr3.reshape((2,3,3))
arr3_reshape

array([[[1, 4, 5],
        [6, 7, 9],
        [3, 4, 5]],

       [[5, 7, 8],
        [2, 3, 4],
        [5, 6, 7]]])

#### Appending & Inserting

In [74]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [76]:
# Create a new array
new_array = np.ones((3,2,3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
appen = np.append(zeroes,new_array,axis=0) # axis 0 = row, axis 1 = column
appen

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [83]:
# Insert

In [85]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [86]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [87]:
inserted_array = np.insert(zeroes,1,new_array,axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

## Delete

In [88]:
arr_4 = np.random.rand(3,2,3)
arr_4

array([[[0.44460892, 0.80512499, 0.82763364],
        [0.77616722, 0.24969337, 0.95458507]],

       [[0.88237154, 0.4255314 , 0.96508861],
        [0.3305999 , 0.66051858, 0.69984642]],

       [[0.4028114 , 0.50334474, 0.80362963],
        [0.62611479, 0.62768123, 0.17419705]]])

In [94]:
# delete the array
arr_5 = np.delete(arr_4,0,axis=1)
arr_5

array([[[0.77616722, 0.24969337, 0.95458507]],

       [[0.3305999 , 0.66051858, 0.69984642]],

       [[0.62611479, 0.62768123, 0.17419705]]])

In [95]:
np.save("new_array",arr_5)

In [96]:
np.load("new_array.npy")

array([[[0.77616722, 0.24969337, 0.95458507]],

       [[0.3305999 , 0.66051858, 0.69984642]],

       [[0.62611479, 0.62768123, 0.17419705]]])